spring:
  application:
    name: zob-backend
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800
    redirectTokenExpiration: 600
  profiles:
    active: dev
